### PR TITLE
Added ncbigenomedownload nf-core module

### PR DESCRIPTION
**Pull request by FernandoDuarteF**
Added ncbigenomedownload nf-core module and modified `main.nf`, `modules.config`, and `gffread.nf` accordingly. Also changed `path accessions` to `val accessions` in `ncbigenomedownload/main.nf`, so that accession strings can be used.

### CODE REVIEW

**Comment by FernandoDuarteF** [comment]
Add a params option for group input (right now `"invertebrate"` as default)

**Comment by chriswyatt1** [comment]
Maybe the groups input could be set to `all`? Not sure if we want to fix this on invertebrate.

Or we need a flag to set this in the pipeline.

**Comment by FernandoDuarteF** [comment]
> Maybe the groups input could be set to `all`? Not sure if we want to fix this on invertebrate.
> 
> Or we need a flag to set this in the pipeline.

I added a "groups" option to `nextflow.config` which is set to `"all"` by default.

**Comment by chriswyatt1** [comment]
Yeah, not sure why the download would need to specify if you can run with all. But if it works now, then all good

**Pull request merged**
